name: Generate Coverage Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Download dependencies
        run: go mod download

      - name: Run tests & generate coverage
        run: go test -covermode=count -coverprofile=coverage.out $(go list ./... | grep -v "testutils")

      - name: Generate coverage badge (SVG)
        run: |
          python3 generate_badge.py

      - name: Commit and push coverage badge
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Update coverage badge"
          add: "coverage_badge.svg"
          token: ${{ secrets.GITHUB_TOKEN }}
